### ISSUE TITLE
JQuery&Bootstrap&StaticFileの設定

### ISSUE THREAD

**Issue by mi-TSUKASA** [mi-TSUKASA/TodoApp_Golang#10]
JQuery&Bootstrap&StaticFileの設定　[https://www.udemy.com/course/golang-webgosql/learn/lecture/23515268#overview](https://www.udemy.com/course/golang-webgosql/learn/lecture/23515268#overview)
webサーバー終わり次第お願いします。

**Comment by aianman4823** [comment]
[https://github.com/mi-TSUKASA/TodoApp_Golang/pull/12](https://github.com/mi-TSUKASA/TodoApp_Golang/pull/12)
