### ISSUE TITLE
レイアウトの共通化

### ISSUE THREAD

**Issue by mi-TSUKASA** [mi-TSUKASA/TodoApp_Golang#13]
すみませんレイアウトの共通化[https://www.udemy.com/course/golang-webgosql/learn/lecture/23515272#overview](https://www.udemy.com/course/golang-webgosql/learn/lecture/23515272#overview)の部分も続けてお願いします！

**Comment by aianman4823** [comment]
@mi-TSUKASA 
はいよ！
土日ですすめようとおもいます！

**Comment by mi-TSUKASA** [comment]
@aianman4823 
ありがとうございます！よろしくお願いします！
