### ISSUE TITLE
ユーザー登録ページの作成

### ISSUE THREAD

**Issue by mi-TSUKASA** [mi-TSUKASA/TodoApp_Golang#15]
ユーザーの登録ページを作ります。[https://www.udemy.com/course/golang-webgosql/learn/lecture/23515384#overview](https://www.udemy.com/course/golang-webgosql/learn/lecture/23515384#overview)

**Comment by mi-TSUKASA** [comment]
@aianman4823 
明日やります！

**Comment by mi-TSUKASA** [comment]
@aianman4823 
遅い上にまだできてないです、すみません！
UI部分を作成しているんですけど、動画通りにならなくて困ってます。。
何回も見返したり、もう一回ブランチを作り直したりしたんですが、どこが間違ってるかわかりません。
確認をお願いしたいんですけど、この場合コードはどのように送ったらいいですか？一回プッシュしますか？

**Comment by aianman4823** [comment]
@mi-TSUKASA 
確認しよう
明日インターンやから、火曜日にやろう！
コードは今まで通り、プルリクエスト出してもらったら大丈夫やで！

**Comment by mi-TSUKASA** [comment]
@aianman4823 
了解です！ありがとうございます！
