### ISSUE TITLE
ログアウトの実装

### ISSUE THREAD

**Issue by mi-TSUKASA** [mi-TSUKASA/TodoApp_Golang#20]
[https://www.udemy.com/course/golang-webgosql/learn/lecture/23515398#overview](https://www.udemy.com/course/golang-webgosql/learn/lecture/23515398#overview)
これやります！

**Comment by mi-TSUKASA** [comment]
明日になるかもしれないです。。🙏

**Comment by aianman4823** [comment]
@mi-TSUKASA 
はいよーー！

**Comment by aianman4823** [comment]
@mi-TSUKASA 
コメントしようと思ったら間違えてcloseしちゃった！
気にしないで！

**Comment by aianman4823** [comment]
LGTM
