### ISSUE TITLE
User.goの作成

### ISSUE THREAD

**Issue by mi-TSUKASA** [mi-TSUKASA/TodoApp_Golang#5]
User.goを作ります

**Comment by mi-TSUKASA** [comment]
@aianman4823 
わからないです
`var Config ConfigList

func init() {
	LoadConfig()
	utils.LoggingSettings(Config.LogFile)
}

func LoadConfig() {
	cfg, err := ini.Load("config.ini")
	if err != nil {
		log.Fatalln(err)
	}
	Config = ConfigList{
		Port:      cfg.Section("web").Key("port").MustString("8080"),
		SQLDriver: cfg.Section("db").Key("driver").String(),
		DbName:    cfg.Section("db").Key("name").String(),
		LogFile:   cfg.Section("web").Key("logfile").String(),
	}
}`

**Comment by mi-TSUKASA** [comment]
@aianman4823 
`var Config ConfigList

func init() {
	LoadConfig()
	utils.LoggingSettings(Config.LogFile)
}

func LoadConfig() {
	cfg, err := ini.Load("config.ini")
	if err != nil {
		log.Fatalln(err)
	}
	Config = ConfigList{
		Port:      cfg.Section("web").Key("port").MustString("8080"),
		SQLDriver: cfg.Section("db").Key("driver").String(),
		DbName:    cfg.Section("db").Key("name").String(),
		LogFile:   cfg.Section("web").Key("logfile").String(),
	}
}`

**Comment by mi-TSUKASA** [comment]
`var Config ConfigList`

**Comment by mi-TSUKASA** [comment]
```
var Config ConfigList

func init() {
	LoadConfig()
	utils.LoggingSettings(Config.LogFile)
}

func LoadConfig() {
	cfg, err := ini.Load("config.ini")
	if err != nil {
		log.Fatalln(err)
	}
	Config = ConfigList{
		Port:      cfg.Section("web").Key("port").MustString("8080"),
		SQLDriver: cfg.Section("db").Key("driver").String(),
		DbName:    cfg.Section("db").Key("name").String(),
		LogFile:   cfg.Section("web").Key("logfile").String(),
	}
}
```

**Comment by mi-TSUKASA** [comment]
@aianman4823 
木曜日までに完成させます

**Comment by aianman4823** [comment]
@mi-TSUKASA 
このブランチをチェックしてからTodo.goの作成にうつっても大丈夫？？
base.goとかmain.goとかのコードが全部依存関係残っちゃってるからさ
todo_base.goとか自分で作成して、そっちを利用する形にカスタマイズする？？

**Comment by mi-TSUKASA** [comment]
@aianman4823 
返信遅くなって本当すみません！！
了解です！じゃあ、僕のブランチできてから作成お願いします。
今日中に終わると思います。申し訳ないです。

**Comment by aianman4823** [comment]
@mi-TSUKASA 
全然問題ないよ
俺でできるところは進めて行っときます！

**Comment by mi-TSUKASA** [comment]
@aianman4823 
すみません！お願いします！🙏

**Comment by aianman4823** [comment]
LGTM
