### ISSUE TITLE
Todo.goの作成

### ISSUE THREAD

**Issue by mi-TSUKASA** [mi-TSUKASA/TodoApp_Golang#6]
Todo.goの作成をお願いします。
[https://www.udemy.com/course/golang-webgosql/learn/lecture/23514970#overview](https://www.udemy.com/course/golang-webgosql/learn/lecture/23514970#overview)

**Comment by mi-TSUKASA** [comment]
@aianman4823 
木曜日までにお願いできますか？

**Comment by aianman4823** [comment]
@mi-TSUKASA 
かなりtodoタスクとuserタスクで依存関係あるみたいだけど大丈夫？？
コンフリクトめっちゃするかも

**Comment by aianman4823** [comment]
@mi-TSUKASA 
タスクが終わったら閉じるの宜しくね！

**Comment by mi-TSUKASA** [comment]
@aianman4823 
すみません！了解です！
