### ISSUE TITLE
webサーバーの立ち上げをします

### ISSUE THREAD

**Issue by mi-TSUKASA** [mi-TSUKASA/TodoApp_Golang#9]
「130. 4-1 Server StartServer」[https://www.udemy.com/course/golang-webgosql/learn/lecture/23515266#overview](https://www.udemy.com/course/golang-webgosql/learn/lecture/23515266#overviewl)
学校のレポートあるので明日やります。すみません

**Comment by aianman4823** [comment]
そんな焦らんでええてw
pmはみやけなんやから

**Comment by aianman4823** [comment]
マージしました!
